"""Generator for handler_<name>.py files."""

from pathlib import Path
from typing import Any, Dict, List

HANDLER_TEMPLATE = '''"""
Auto-generated handler for resource: {resource_name}
Generated at: {timestamp}

This file is generated by the Flash build process. Do not edit manually.
"""

from tetra_rp.runtime.generic_handler import create_handler

# Import all functions/classes that belong to this resource
{imports}

# Function registry for this handler
FUNCTION_REGISTRY = {{
{registry}
}}

# Create configured handler
handler = create_handler(FUNCTION_REGISTRY)

if __name__ == "__main__":
    import runpod
    runpod.serverless.start({{"handler": handler}})
'''


class HandlerGenerator:
    """Generates handler_<name>.py files for each resource config."""

    def __init__(self, manifest: Dict[str, Any], build_dir: Path):
        self.manifest = manifest
        self.build_dir = build_dir

    def generate_handlers(self) -> List[Path]:
        """Generate all handler files."""
        handler_paths = []

        for resource_name, resource_data in self.manifest.get("resources", {}).items():
            handler_path = self._generate_handler(resource_name, resource_data)
            handler_paths.append(handler_path)

        return handler_paths

    def _generate_handler(
        self, resource_name: str, resource_data: Dict[str, Any]
    ) -> Path:
        """Generate a single handler file."""
        handler_filename = f"handler_{resource_name}.py"
        handler_path = self.build_dir / handler_filename

        # Get timestamp from manifest
        timestamp = self.manifest.get("generated_at", "")

        # Generate imports section
        imports = self._generate_imports(resource_data.get("functions", []))

        # Generate function registry
        registry = self._generate_registry(resource_data.get("functions", []))

        # Format template
        handler_code = HANDLER_TEMPLATE.format(
            resource_name=resource_name,
            timestamp=timestamp,
            imports=imports,
            registry=registry,
        )

        handler_path.write_text(handler_code)
        return handler_path

    def _generate_imports(self, functions: List[Dict[str, Any]]) -> str:
        """Generate import statements for functions."""
        imports = []

        for func in functions:
            module = func.get("module")
            name = func.get("name")

            if module and name:
                imports.append(f"from {module} import {name}")

        return "\n".join(imports) if imports else "# No functions to import"

    def _generate_registry(self, functions: List[Dict[str, Any]]) -> str:
        """Generate function registry dictionary."""
        if not functions:
            return "    # No functions registered"

        registry_lines = []

        for func in functions:
            name = func.get("name")
            registry_lines.append(f'    "{name}": {name},')

        return "\n".join(registry_lines)
