name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read
  security-events: write

jobs:
  # Use the shared quality gates workflow
  quality-gates:
    name: Quality Gates
    uses: ./.github/workflows/shared-quality-gates.yml
    permissions:
      contents: read
      actions: read
      security-events: write

  # Job that runs only on PRs to provide final status
  pr-status:
    name: PR Status
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [quality-gates]
    steps:
      - name: All checks passed
        run: |
          echo "All CI checks passed!"
          echo "This PR is ready for review and merge!"
